---
title: 起步
permalink: database
category: 数据库
---

= 起步

toc::[]

通过强大的 link:query-builder[Query Builder]，link:lucid[Lucid ORM]， link:migrations[Migrations]， link:seeds-and-factories[Factories] 和 link:seeds-and-factories[Seeds]，AdonisJs 创建数据驱动的应用程序的过程被大大的简化。

在本指南中，我们将学习设置和使用 *数据库提供者*。

NOTE: 数据提供者的内部使用了 link:https://knexjs.org[Knex.js, window="_blank"]，所以如果你需要更详细的信息，请阅读 Knex 的文档。

== 支持的数据库
支持的数据库及其对应的驱动程序列表如下：

[options="header", cols="25, 75"]
|====
| 数据库 | NPM 驱动程序
| MariaDB | `npm i mysql` or `npm i mysql2`
| MSSQL | `npm i mssql`
| MySQL | `npm i mysql` or `npm i mysql2`
| Oracle | `npm i oracledb`
| PostgreSQL | `npm i pg`
| SQLite3 | `npm i sqlite3`
|====

== 设置

=== 安装
如果未安装 *数据库提供者* (*Lucid*)，请从 npm 的以下位置拉取：

[source, bash]
----
> adonis install @adonisjs/lucid
----

接下来，在 `start/app.js` 文件中注册以下提供者：

.start/app.js
[source, js]
----
const providers = [
  '@adonisjs/lucid/providers/LucidProvider'
]

const aceProviders = [
  '@adonisjs/lucid/providers/MigrationsProvider'
]
----

NOTE: 默认情况下，许多 AdonisJs 样板代码都安装了 *Lucid*。

=== 配置
*数据库提供者* 默认使用 `sqlite` 连接。

可以通过 `config/database.js` 文件设置默认连接：

.config/database.js
[source, js]
----
module.exports = {
  connection: 'mysql',
}
----

支持所有的 Knex link:http://knexjs.org/#Installation-client[配置选型, window="_blank"]。

== 基本例子

AdonisJs link:query-builder[Query Builder] 具有 *流畅的* API，这意味着你可以链接/附加 JavaScript 方法来创建 SQL 查询。

例如，要选择并以JSON形式返回所有用户：
[source, js]
----
const Database = use('Database')

Route.get('/', async () => {
  return await Database.table('users').select('*')
})
----

=== Where 字句
要向查询添加where子句，请链接一个 `where` 方法：

[source, js]
----
Database
  .table('users')
  .where('age', '>', 18)
----

要添加另一个 where 字句，请链接 `orWhere` 方法：

[source, js]
----
Database
  .table('users')
  .where('age', '>', 18)
  .orWhere('vip', true)
----

有关完整的 API 参考，请参阅 link:query-builder[Query Builder] 文档。

== 多个连接
默认情况下，AdonisJs 在进行数据库查询时会使用 `config/database.js` 文件中定义的 `连接` 值。

你可以在运行时选择 `config/database.js` 文件中定义的任一连接进行查询：

[source, js]
----
Database
  .connection('mysql')
  .table('users')
----

NOTE: 由于AdonisJs将连接池用于重用，因此除非进程终止，否则将维护所有已使用的连接。

要关闭连接，请调用 `close` 方法并传递任何连接名称：

[source, js]
----
const users = await Database
  .connection('mysql')
  .table('users')

// 稍后关闭连接
Database.close(['mysql'])
----

== 表前缀
*数据库提供者* 可以通过在 `config/database.js` 文件中定义 `前缀` 值来自动为表名添加前缀：

.config/database.js
[source, js]
----
module.exports = {
  connection: 'sqlite',

  sqlite: {
    client: 'sqlite3',
    prefix: 'my_'
  }
}
----

现在，所有在 `sqlite` 连接上的查询都将以 `my_` 作为表前缀：

[source, js]
----
await Database
  .table('users')
  .select('*')
----

.SQL Output
[source, sql]
----
select * from `my_users`
----

==== withOutPrefix
如果定义了 `前缀` 值，你可以通过调用 `withOutPrefix` 忽略它：

[source, js]
----
await Database
  .withOutPrefix()
  .table('users')
----

== 调试
在开发和生成中调试数据库查询都非常方便。

让我们来看看调试查询的可用策略。

=== 全局
在 `database/config.js` 文件中设置 `debug: true` 可以全局调试所有查询：

.config/database.js
[source, js]
----
module.exports = {
  connection: 'sqlite',

  sqlite: {
    client: 'sqlite3',
    connection: {},
    debug: true
  }
}
----

你还可以通过 *数据库提供者* `query` 事件调试查询。

通过在 `start/hooks.js` 文件中定义一个钩子来监听 `query` 事件：

.start/hooks.js
[source, js]
----
const { hooks } = require('@adonisjs/ignitor')

hooks.after.providersBooted(() => {
  const Database = use('Database')
  Database.on('query', console.log)
})
----

NOTE: 如果 `start/hooks.js` 文件不存在，请创建它。

=== 本地
你可以在运行时监听每个查询的 `query` 事件：

[source, js]
----
await Database
  .table('users')
  .select('*')
  .on('query', console.log)
----

////
=== Slow query logs
Tracking slow SQL queries is helpful to keep your app running smoothly.

AdonisJs makes it easy to track slow SQL queries by listening for the `slow:query` event:

[source, js]
----
Database.on('slow:query', (sql, time) => {
  console.log(`${time}: ${sql.query}`)
})
----

The configuration for slow queries is saved next to the connection settings in the `config/database.js` file:

[source, js]
----
module.exports = {
  connection: 'sqlite',

  sqlite: {
    client: 'sqlite3',
    slowQuery: {
      enabled: true,
      threshold: 5000
    }
  }
}
----
////
