---
permalink: query-builder
title: 查询构造器
category: 数据库
---

= 查询构造器

toc::[]

AdonisJs *查询构造器* 提供了统一的语法，让 JavaScript 方法可以与 SQL 数据库进行交互。

本指南是对 *查询构造器* 上所有可用方法的参考。

TIP: 有关支持的数据库，配置选项以及如何调试 SQL 查询的信息，请参加 数据库 link:database[起步]。

== 介绍
即使你精通 SQL，编写 SQL 查询也可能很乏味。

=== 语法抽象

想像一下，你的所有查询都是针对 MySQL 编写的，稍后你会被要求将所有内容迁移到 PostgreSQL 上。你必须重写/修改你的 MySQL 查询，以确保它们仍然适用于 PostgreSQL。

*查询构造器* 抽象了特定于连接的语法，因此你可以自由的专注于应用程序功能，而不是 SQL 语言的变体（类似语法糖）。

=== 条件查询
另一个问题是使用条件块构建增量查询：

.不使用查询构造器
[source, javascript]
----
const sql = 'SELECT * FROM `users`'

if (username) {
  sql += ' WHERE `username` = ' + username
}
----

.使用查询构造器
[source, javascript]
----
const query = Database.table('users')

if (username) {
  query.where('username', username)
}
----

== 基本例子
这是一个使用 *查询构造器* 链接不同方法的基本示例：

[source, javascript]
----
const Database = use('Database')

class UserController {

  async index (request, response) {
    return await Database
      .table('users')
      .where('username', 'john')
      .first()
  }

}
----

== 选择
`select` 方法定义要为给定查询选择的字段：

[source, javascript]
----
await Database.select('id', 'username').from('users')
// 或者
await Database.select('*').from('users')
----

.SQL 输出
[source, sql]
----
select `id`, `username` from `users`
select * from `users`
----

你可以像这样定义查询 *别名*：
[source, js]
----
await Database.select('username as uname')
----

== Where 子句
*查询构造器* 提供了许多动态方法来添加 *where* 子句。

它还可以通过传递 *闭包* 或 *其他查询*（而不是实际值） 来支持子查询。

有关 `where` 的详细信息，请参阅 Knex 的 link:http://knexjs.org/#Builder-wheres[文档, window="_blank"]。

NOTE: 在 SQL 编译期间，传递 `undefined` 给 `where` 子句将会导致错误，因此请确保在传递动态值之前不要将其定义为 `undefined`。

==== where

[source, javascript]
----
const users = await Database.from('users').where('id', 1)
// 或者
const users = await Database.from('users').where({ id: 1 })
----

你可以将比较运算符传递给 `where` 子句，如下所示：

[source, javascript]
----
const adults = await Database
  .from('users')
  .where('age', '>', 18)
----

==== where (带回调)
你可以将回调传递给 `where` 子句，以便对回调中包含的所有子句进行分组：

[source, javascript]
----
await Database.from('users').where(function () {
  this
    .where('id', 1)
    .orWhere('id', '>', 10)
})
----

.SQL 输出
[source, sql]
----
select * from `users` where (`id` = 1 or `id` > 10)
----

==== whereNot
[source, javascript]
----
await Database
  .from('users')
  .whereNot('age', '>', 15)

// 或者
await Database
  .from('users')
  .whereNot({username: 'foo'})
----

==== whereIn
[source, javascript]
----
await Database
  .from('users')
  .whereIn('id', [1,2,3])
----

==== whereNotIn
[source, javascript]
----
await Database
  .from('users')
  .whereNotIn('id', [1,2,3])
----

==== whereNull
[source, javascript]
----
await Database
  .from('users')
  .whereNull('deleted_at')
----

==== whereNotNull
[source, javascript]
----
await Database
  .from('users')
  .whereNotNull('created_at')
----

==== whereExists
[source, javascript]
----
await Database.from('users').whereExists(function () {
  this.from('accounts').where('users.id', 'accounts.user_id')
})
----

==== whereNotExists
[source, javascript]
----
await Database.from('users').whereNotExists(function () {
  this.from('accounts').where('users.id', 'accounts.user_id')
})
----

==== whereBetween
[source, javascript]
----
await Database
  .table('users')
  .whereBetween('age', [18, 32])
----

==== whereNotBetween
[source, javascript]
----
await Database
  .table('users')
  .whereNotBetween('age', [45, 60])
----

==== whereRaw
`.where(Database.raw(query))` 的便利助手：

[source, javascript]
----
await Database
  .from('users')
  .whereRaw('id = ?', [20])
----

== 连接

==== innerJoin

[source, javascript]
----
await Database
  .table('users')
  .innerJoin('accounts', 'user.id', 'accounts.user_id')
----

你还可以传递回调以构建连接：

[source, javascript]
----
await Database
  .table('users')
  .innerJoin('accounts', function () {
    this
      .on('users.id', 'accounts.user_id')
      .orOn('users.id', 'accounts.owner_id')
  })
----

==== leftJoin
[source, js]
----
Database
  .select('*')
  .from('users')
  .leftJoin('accounts', 'users.id', 'accounts.user_id')
----

==== leftOuterJoin
[source, js]
----
await Database
  .select('*')
  .from('users')
  .leftOuterJoin('accounts', 'users.id', 'accounts.user_id')
----

==== rightJoin
[source, js]
----
await Database
  .select('*')
  .from('users')
  .rightJoin('accounts', 'users.id', 'accounts.user_id')
----

==== rightOuterJoin
[source, js]
----
await Database
  .select('*')
  .from('users')
  .rightOuterJoin('accounts', 'users.id', 'accounts.user_id')
----

==== outerJoin
[source, js]
----
await Database
  .select('*')
  .from('users')
  .outerJoin('accounts', 'users.id', 'accounts.user_id')
----

==== fullOuterJoin
[source, js]
----
await Database
  .select('*')
  .from('users')
  .fullOuterJoin('accounts', 'users.id', 'accounts.user_id')
----

==== crossJoin
[source, js]
----
await Database
  .select('*')
  .from('users')
  .crossJoin('accounts', 'users.id', 'accounts.user_id')
----

==== joinRaw
[source, js]
----
await Database
  .select('*')
  .from('accounts')
  .joinRaw('natural full join table1').where('id', 1)
----

== 排序和限制

==== distinct
[source, javascript]
----
await Database
  .table('users')
  .distinct('age')
----

==== groupBy
[source, javascript]
----
await Database
  .table('users')
  .groupBy('age')
----

==== groupByRaw
[source, javascript]
----
await Database
  .table('users')
  .groupByRaw('age, status')
----

==== orderBy(column, [direction=asc])
[source, javascript]
----
await Database
  .table('users')
  .orderBy('id', 'desc')
----

==== orderByRaw(column, [direction=asc])
[source, javascript]
----
await Database
  .table('users')
  .orderByRaw('col NULLS LAST DESC')
----

==== having(column, operator, value)
NOTE: 必须在 `groupBy()` 之前调用 `having()`。

[source, javascript]
----
await Database
  .table('users')
  .groupBy('age')
  .having('age', '>', 18)
----

==== offset/limit(value)
[source, javascript]
----
await Database
  .table('users')
  .offset(11)
  .limit(10)
----

== 插入

==== insert(values)
`insert` 操作创建一行并返回其新创建的 `id`：
[source, javascript]
----
const userId = await Database
  .table('users')
  .insert({username: 'foo', ...})
----

如果是批量插入，则返回第一条记录的 `id`（这是 MySQL 本身的限制，请参阅 link:http://dev.mysql.com/doc/refman/5.6/en/information-functions.html#function_last-insert-id[LAST_INSERT_ID, window="_blank"]）：

[source, javascript]
----
// 批量插入
const firstUserId = await Database
  .from('users')
  .insert([{username: 'foo'}, {username: 'bar'}])
----

==== into(tableName)
插入数据库行时，`into` 方法比 `table/from` 更具可读性：

[source, javascript]
----
const userId = await Database
  .insert({username: 'foo', ...})
  .into('users')
----

=== PostgreSQL 返回列
对于 PostgreSQL，你必须显示定义返回列（所有其他数据库客户端都忽略此语句）：

[source, javascript]
----
const userId = await Database
  .insert({ username: 'virk' })
  .into('users')
  .returning('id')
----

== 更新
所有更新操作都返回受影响的行数：

[source, javascript]
----
const affectedRows = await Database
  .table('users')
  .where('username', 'tutlage')
  .update('lastname', 'Virk')
----

要更新多个列，请将这些列/值作为对象传递：

[source, javascript]
----
const affectedRows = await Database
  .table('users')
  .where('username', 'tutlage')
  .update({ lastname: 'Virk', firstname: 'Aman' })
----

== 删除

==== delete
删除操作还会返回受影响的行数：

[source, javascript]
----
const affectedRows = await Database
  .table('users')
  .where('username', 'tutlage')
  .delete()
----

NOTE: 由于 `delete` 是 JavaScript 的一个保留关键字，所以你也可以使用代替的 `del()` 方法。

==== truncate
Truncate 删除所有表行，将表的自动增量 id 重置为 `0`：

[source, javascript]
----
await Database.truncate('users')
----

== 分页
*查询构造器* 提供了分页数据库结果的便捷方法。

==== forPage(page, [limit=20])
[source, javascript]
----
const users = await Database
  .from('users')
  .forPage(1, 10)
----

==== paginate(page, [limit=20])
[source, javascript]
----
const results = await Database
  .from('users')
  .paginate(2, 10)
----

NOTE: `paginate` 方法的输出和 `forPage` 方法不同。

.Output
[source, javascript]
----
{
  total: '',
  perPage: '',
  lastPage: '',
  page: '',
  data: [{...}]
}
----

NOTE: 如果使用了 *PostgreSQL*，则 `total` 键将是一个字符串，因为 JavaScript 无法在本地处理 `bigint`（有关推荐的解决方案，请参阅 link:https://github.com/adonisjs/adonis-lucid/issues/339#issuecomment-387399508[此问题, window="_blank"]）。

== 数据库事务
数据库事务是安全的操作，在你明确提交更改之前，这些操作不会反映在数据库中。

==== beginTransaction
`beginTransaction` 方法返回事务对象，用于执行任何查询：

[source, javascript]
----
const trx = await Database.beginTransaction()
await trx.insert({username: 'virk'}).into('users')

await trx.commit() // 提交时将进行插入查询
await trx.rollback() // 不会插入任何东西
----

==== transaction
你还可以将事务包装在回调中：

[source, javascript]
----
await Database.transaction(async (trx) => {
  await trx.insert({username: 'virk'}).into('users')
})
----

NOTE: 你无需在此回调中手动调用 `commit` 或者 `rollback`。

如果你的任何查询引发了错误，则事务将会自动回滚，否则将被提交。

== 聚合

*查询构造器* 暴露了 Knex link:http://knexjs.org/#Builder-count[聚合方法, window="_blank"] 的全部功能。

==== count()
[source, javascript]
----
const count = await Database
  .from('users')
  .count()                                      // returns array

const total = count[0]['count(*)']              // returns number

// 列数
const count = await Database
  .from('users')
  .count('id')                                  // returns array

const total = count[0]['count("id")']           // returns number

// 以名称计算列数
const count = await Database
  .from('users')
  .count('* as total')                          // returns array

const total = count[0].total                    // returns number
----

==== countDistinct
`countDistinct` 与 `count` 相同，但是添加了一个 `distinct` 表达式：

[source, javascript]
----
const count = await Database
  .from('users')
  .countDistinct('id')                          // returns array

const total = count[0]['count(distinct "id")']  // returns number
----

==== min
[source, javascript]
----
await Database.from('users').min('age')         // returns array
await Database.from('users').min('age as a')    // returns array
----

==== max
[source, javascript]
----
await Database.from('users').max('age')         // returns array
await Database.from('users').max('age as a')    // returns array
----

==== sum
[source, javascript]
----
await Database.from('cart').sum('total')        // returns array
await Database.from('cart').sum('total as t')   // returns array
----

==== sumDistinct
[source, javascript]
----
await Database.from('cart').sumDistinct('total')      // returns array
await Database.from('cart').sumDistinct('total as t') // returns array
----

==== avg
[source, javascript]
----
await Database.from('users').avg('age')         // returns array
await Database.from('users').avg('age as age')  // returns array
----

==== avgDistinct
[source, javascript]
----
await Database.from('users').avgDistinct('age')         // returns array
await Database.from('users').avgDistinct('age as age')  // returns array
----

==== increment
将列值增加 `1`：

[source, javascript]
----
await Database
  .table('credits')
  .where('id', 1)
  .increment('balance', 10)
----

==== decrement
将列值减少 `1`：

[source, javascript]
----
await Database
  .table('credits')
  .where('id', 1)
  .decrement('balance', 10)
----

=== 聚合助手

AdonisJs *查询构造器* 还扩展了 Knex 的查询聚合，为常见的聚合查询提供了有用的快捷方法。这些辅助方法会结束查询构造器链并返回一个值。

所有助手程序都接受用于聚合的列名。如果可能，*查询构造器* 将为列名选择默认值。

有些方法，例如 `sum()`，需要列名。

底层的 Knex 查询构造器定义了以下方法：`count()`, `countDistinct()`, `avg()`, `avgDistinct()`, `sum()`, `sumDistinct()`, `min()` 和 `max()`。为了避免混淆和命名冲突，*查询构造器* 在其聚合辅助方法上加了 `get` 前缀（例如 `getCount`），

==== getCount(columnName = '*')
[source, javascript]
----
const total = await Database
  .from('users')
  .getCount()                                   // returns number
----

==== getCountDistinct(columnName)
[source, javascript]
----
const total = await Database
  .from('users')
  .countDistinct('id')                          // returns number
----

==== getMin(columnName)
[source, javascript]
----
await Database.from('users').getMin('age')      // returns a number
----

==== getMax(columnName)
[source, javascript]
----
await Database.from('users').getMax('age')      // returns number
----

==== getSum(columnName)
[source, javascript]
----
await Database.from('cart').getSum('total')     // returns number
----

==== getSumDistinct(columnName)
[source, javascript]
----
await Database.from('cart').getSumDistinct('total')   // returns number
----

==== getAvg(columnName)
[source, javascript]
----
await Database.from('users').getAvg('age')      // returns number
----

==== getAvgDistinct(columnName)
[source, javascript]
----
await Database.from('users').getAvgDistinct('age')      // returns number
----


== 助手

==== pluck(column)
`pluck` 方法将返回选定列的值数组：
[source, javascript]
----
const usersIds = await Database.from('users').pluck('id')
----

==== first
`first` 方法向查询添加一条 `limit 1` 子句：

[source, javascript]
----
await Database.from('users').first()
----

==== clone
克隆当前查询链以供以后使用：

[source, javascript]
----
const query = Database
  .from('users')
  .where('username', 'virk')
  .clone()

// 之后
await query
----

==== columnInfo
返回给定列的信息：

[source, javascript]
----
const username = await Database
  .table('users')
  .columnInfo('username')
----

== 子查询
[source, javascript]
----
const subquery = Database
  .from('accounts')
  .where('account_name', 'somename')
  .select('account_name')

const users = await Database
  .from('users')
  .whereIn('id', subquery)
----

[source, sql]
----
select * from `users` where `id` in (select `account_name` from `accounts` where `account_name` = 'somename')
----

== 原生查询
`Database.raw` 方法应该用于运行原生 SQL 查询：

[source, js]
----
await Database
  .raw('select * from users where username = ?', [username])
----

== 关闭连接
可以通过调用 `close` 方法来关闭数据库连接。默认情况下，此方法关闭所有打开的数据库连接。

要关闭指定的连接，请传递一个连接名称的数组：

[source, js]
----
Database.close() // all

Database.close(['sqlite', 'mysql'])
----
