---
title: 填充 & 假数据
permalink: seeds-and-factories
category: 数据库
---

= 填充 & 假数据

toc::[]

译者注：下文中为了减轻理解负担，个别词汇不做翻译，例如seeds（种子） 和 factories（工厂）等，它们分别用于填充数据和伪造假数据。

一旦你准备好 link:migrations[迁移] 的数据库 schema 后，下一步就是添加一些数据。这就是数据库 *seeds* 和 *factories* 发挥作用的地方。

== 填充（Seeds）
填充是包含 `run` 方法的 JavaScript 类。在该 `run` 方法中，你可以自由的编写填充所需的任何与数据库相关的操作。

与迁移一样，使用以下 `adonis make` 命令创建 seed 文件：

[source, bash]
----
> adonis make:seed User
----

.Output
[source, bash]
----
✔ create  database/seeds/UserSeeder.js
----

现在打开此文件并在其中输入以下代码：

.database/seeds/UserSeeder.js
[source, js]
----
const Factory = use('Factory')
const Database = use('Database')

class UserSeeder {
  async run () {
    const users = await Database.table('users')
    console.log(users)
  }
}

module.exports = UserSeeder
----

通过调用 `adonis seed` 命令来运行 seed 文件，该命令将对所有的 seed 文件执行 `run` 方法。

由于你可以在 seed 文件中编写任何与数据库相关的代码，并用命令行执行它们，因此它们有助于从实际应用程序代码中卸载某些任务。

然而，当与 *Factories* 结合一起时，seeds 的真正力量就会被释放。

== 假数据（Factories）
Factories 定义用于生成虚拟数据的数据结构（blueprint 蓝图）。

Factory blueprints 在 `database/factory.js` 文件内设置：

[source, js]
----
const Factory = use('Factory')
const Hash = use('Hash')

Factory.blueprint('App/Models/User', async (faker) => {
  return {
    username: faker.username(),
    email: faker.email(),
    password: await Hash.make(faker.password())
  }
})
----

从 factory blueprint 生成模型实例时，使用 blueprint 内定义的键预填充模型的属性：

[source, js]
----
const user = await Factory
  .model('App/Models/User')
  .create()
----

可以同时生成许多模型实例：

[source, js]
----
const usersArray = await Factory
  .model('App/Models/User')
  .createMany(5)
----

=== Creating Relationships 建立关系
假设我们要创建一个 `User` 模型，并将其与 `Post` 关联。

NOTE: 对于以下示例，必须首先在 User 模型上定义一个 `posts` 关系。 link:relationships[这里] 可以了解更多关于关系的信息。

首先，在 `database/factory.js` 文件中为两个模型创建 blueprints。

.database/factory.js
[source, js]
----
// User blueprint
Factory.blueprint('App/Models/User', (faker) => {
  return {
    username: faker.username(),
    password: faker.password()
  }
})

// Post blueprint
Factory.blueprint('App/Models/Post', (faker) => {
  return {
    title: faker.sentence(),
    body: faker.paragraph()
  }
})
----

然后，创建一个 `User` 和一个 `Post`，并将两个模型相互关联：

[source, js]
----
const user = await Factory.model('App/Models/User').create()
const post = await Factory.model('App/Models/Post').make()

await user.posts().save(post)
----

你可能会注意到我们在 `Post` blueprint 上使用了 `make` 方法。

与 `create` 方法不同，`make` 方法不会将 `Post` 模型持久化到数据库，而是返回一个未保存的 `Post` 模型实例，该模型预先填充了假数据（调用 `.posts().save()` 方法时保存 `Post` 模型）。

== 填充命令
一下是可用的 seed 命令列表。

[options="header", cols="30, 20, 50"]
|====
| 命令 | 选项 | 描述
| `adonis make:seed` | 无 | 创建一个新的 seed 文件。
| `adonis seed` | `--files` | 执行 seed 文件（你可以选择传递 `--files` 加要执行的逗号分隔列表，否则，将执行所有文件）。
|====

== 模型工厂 API
下面是使用 link:lucid[Lucid 模型] 工厂时可用方法的列表。

==== create
持久化并返回模型实例：

[source, js]
----
await Factory
  .model('App/Models/User')
  .create()
----

==== createMany
持久化并返回多个模型实例：

[source, js]
----
await Factory
  .model('App/Models/User')
  .createMany(3)
----

==== make
返回模型实例，但不将其持久化到数据库：

[source, js]
----
await Factory
  .model('App/Models/User')
  .make()
----

==== makeMany
返回模型实例的数组，但不将其持久化到数据库：

[source, js]
----
await Factory
  .model('App/Models/User')
  .makeMany(3)
----

== 没有 Lucid 的用法
如果你的应用程序不使用 link:lucid[Lucid 模型]，你仍然可以使用 link:query-builder[数据库提供者] 生成 factory 数据库记录。

==== blueprint

要在不使用 Lucid 的情况下定义 factory blueprint，请将表名作为第一个参数而不是模型名称（例如 `users` 而不是 `App/Models/User`）：

[source, js]
----
Factory.blueprint('users', (faker) => {
  return {
    username: faker.username(),
    password: faker.password()
  }
})
----

==== create
创建了一个表记录：

[source, js]
----
run () {
  await Factory.get('users').create()
}
----

==== table
在运行时定义不同的表名：

[source, js]
----
await Factory
  .get('users')
  .table('my_users')
  .create()
----

==== returning
对于 PostgreSQL，定义一个返回列：

[source, js]
----
await Factory
  .get('users')
  .returning('id')
  .create()
----

==== connection
在运行时选择其他连接：

[source, js]
----
await Factory
  .get('users')
  .connection('mysql')
  .returning('id')
  .create()
----

==== createMany
创建多个记录：

[source, js]
----
await Factory
  .get('users')
  .createMany(3)
----

== 自定义数据
`make`，`makeMany`，`create` 和 `createMany` 接收一个直接传递到你的 blueprints 的自定义数据对象。

例如：

[source, js]
----
const user = await Factory
  .model('App/Models/User')
  .create({ status: 'admin' })
----

在你的 blueprints 中，你的自定义数据对象的使用方式如下：

[source, js]
----
Factory.blueprint('App/Models/User', async (faker, i, data) => {
  return {
    username: faker.username(),
    status: data.status
  }
})
----

== Faker（伪造） API
传递给 factory blueprint 的 `faker` 对象是对 JavaScript link:http://chancejs.com[Chance, window="_blank"] 随机生成器库的引用。

请务必阅读 Chance 的 link:http://chancejs.com[文档, window="_blank"]，以获取可用的 `faker` 方法和属性的完整列表。

== 常见问题
由于 factories 和 seeds 适用于许多不同的用例，你可能对如何/何时使用它们感到困惑，因此这里列出一些常见问题解答。

[ol-spaced]
1. *factories 和 seeds 必须一起使用吗？* +
  不是，Factories 和 seeds 彼此不依赖，可以单独使用。例如，你可以使用 seed 文件将数据从完全不同的应用程序导入到 AdonisJs 应用程序中。

2. *我可以在编写测试时使用 factories 吗？* +
  可以，将 factory provider (`Factory`) 导入到你的测试中，并根据需要使用即可。

3. *我可以只运行选定的 seed 文件吗？* +
  可以，将包含逗号分隔文件名列表的 `--files` 传递给 `adonis seed` 命令，例如：
+
[source, bash]
----
> adonis seed --files='UsersSeeder.js, PostsSeeder.js'
----
