---
title: Redis 缓存
permalink: redis
category: 数据库
---
= Redis

toc::[]

AdonisJs 在 link:https://github.com/luin/ioredis[ioredis, window="_blank"] 的基础上构建了一套更好的发布/订阅 API，为 link:https://redis.io/[Redis, window="blank"] 提供一流的支持。

NOTE: 100% 支持配置、事件 API 和所有的 *ioredis* 方法，有关完整文档，请参阅 link:https://github.com/luin/ioredis[ioredis, window="_blank"]。

== 设置
由于默认情况下未安装 *Redis 提供者*，因此我们需要从以下 `npm` 位置拉取它：

[source, bash]
----
> adonis install @adonisjs/redis
----

接下来，在 `start/app.js` 文件中注册提供者：

.start/app.js
[source, js]
----
const providers = [
  '@adonisjs/redis/providers/RedisProvider'
]
----

NOTE: Redis 配置保存在 `config/redis.js` 文件中，该文件是在安装 *Redis 提供者* 时由 `adonis install` 命令创建的。

== 基本例子
让我们从一个在 Redis 中缓存用户的基本示例开始：

.app/Controllers/Http/UserController.js
[source, js]
----

'use strict'

const Redis = use('Redis')
const User = use('App/Models/User')

class UserController {

  async index () {
    const cachedUsers = await Redis.get('users')
    if (cachedUsers) {
      return JSON.parse(cachedUsers)
    }

    const users = await User.all()
    await Redis.set('users', JSON.stringify(users))
    return users
  }
}
----

NOTE: 上面示例可能不是缓存数据的最佳方法 - 它只是提供了如何使用 Redis 的思路。

== 命令
所有的 link:http://redis.io/commands[Redis 命令, window="_blank"] 都支持 JavaScript 函数，例如：

[source, js]
----
const Redis = use('Redis')

const user = {
  username: 'foo',
  email: 'foo@bar.com'
}

// set user
await Redis.hmset('users', user.username, JSON.stringify(user))

// get user
const user = await Redis.hmget('users', user.username)
----

== 发布/订阅
Redis 内置了对发布/订阅（pub/sub）的支持，以便在同一服务器或跨多个服务器之间共享信息。

AdonisJs 在 Redis 发布/订阅之上提供了一个简洁的 API，以订阅不同的事件并对其进行操作。

在你的 `start/redis.js` 文件中设置 Redis 订阅者：

.start/redis.js
[source, js]
----
'use strict'

const Redis = use('Redis')

Redis.subscribe('music', async (track) => {
  console.log('received track', track)
})
----

NOTE: `start/redis.js` 文件如果不存在，请创建该文件并将其加载到 `server.js`: `.preLoad('start/redis')`。

一旦注册了订阅者，你可以将数据从相同或不同的服务器发布到此频道：

[source, js]
----
const Redis = use('Redis')

Redis.publish('music', track)
----

=== 可用方法
以下是与 Redis 的发布/订阅层交互的方法列表。

NOTE: 给定频道只能拥有一个订阅者。

==== subscribe(channel, listener)
[source, js]
----
Redis.subscribe('music', (track) {
  console.log(track)
})
----

你还可以从 `app/Listeners` 目录传递一个 `file.method` 引用：

[source, js]
----
Redis.subscribe('music', 'Music.newTrack')
----

.app/Listeners/Music.js
[source, js]
----
'use strict'

const Music = exports = module.exports = {}

Music.newTrack = (track) => {
  console.log(track)
}
----

==== psubscribe(pattern, listener)
订阅模式：

[source, js]
----
Redis.psubscribe('h?llo', function (pattern, message, channel) {
})

Redis.publish('hello')
Redis.publish('hallo')
----

==== publish(channel, message)
将消息发布到指定频道：

[source, js]
----
Redis.publish('music', JSON.stringify({
  id: 1,
  title: 'Love me like you do',
  artist: 'Ellie goulding'
}))
----

==== unsubscribe(channel)
取消订阅指定频道：

[source, js]
----
Redis.unsubscribe('music')
----

==== punsubscribe(channel)
取消订阅指定模式：

[source, js]
----
Redis.punsubscribe('hello')
----

== 多个连接
你可以在 `config/redis.js` 文件中定义多个连接的配置，并且可以通过调用 `connection` 方法来使用这些连接：

.config/redis.js
[source, js]
----
module.exports = {
  connection: 'local',

  local: {
    ...
  },

  secondary: {
    host: 'myhost.com',
    port: 6379
  }
}
----

==== connection(name)
使用其他连接进行 Redis 查询：

[source, js]
----
await Redis
  .connection('secondary')
  .get('users')

// 保持对连接的引用
const secondaryConnection = Redis.connection('secondary')
await secondaryConnection.get('users')
----

==== quit(name)
Redis 提供者创建一个连接池以重用现有连接。

你可以通过调用 `quit` 方法，并传递一个连接或连接数组来退出连接：

[source, js]
----
await Redis.quit('primary')
await Redis.quit(['primary', 'secondary'])
----

