---
permalink: routing
title: 路由
category: 基础
---

= 路由

toc::[]

路由使得外界能够通过 URL 与你的应用进行交互。

路由在 `start/routes.js` 文件中注册。

== 基本路由

最基本的路由绑定需要一个 URL 和一个闭包：

.start/routes.js
[source, js]
----
Route.get('/', () => 'Hello Adonis')
----

闭包的返回值将作为响应发送回客户端。

你还可以使用 `controller.method` 签名的方式将路由绑定到控制器：

.start/routes.js
[source, js]
----
Route.get('posts', 'PostController.index')
----

以上的签名 `PostController.index` 指的是 `App/Controllers/Http/PostController.js` 文件的 `index` 方法。

=== 可用的路由方法

资源路由使用不同的 HTTP 动词来指示请求的类型：

[source, js]
----
Route.get(url, closure)
Route.post(url, closure)
Route.put(url, closure)
Route.patch(url, closure)
Route.delete(url, closure)
----

要注册一个相应多个动词的路由，请使用 `Route.route`：

[source, js]
----
Route.route('/', () => {
  //
}, ['GET', 'POST', 'PUT'])
----

要直接渲染视图 (例如：静态页面)，请使用 `Route.on.render`：

[source, js]
----
Route.on('/').render('welcome')
----

在以上的实力最后你，当路由 `/` 加载是，将直接显示 `resources/view/welcome.edge` 视图文件。

== 路由参数

=== 必要参数

对于动态路由，你可以这样定义路由参数：

.start/routes.js
[source, js]
----
Route.get('posts/:id', ({ params }) => {
  return `Post ${params.id}`
})
----

以上示例中, `:id` 是一个路由参数。

然后通过 `params` 对象检索其值。

=== 可选参数

要定义可选的路由参数，请在定义结尾附加一个 `?` 符号：

.start/routes.js
[source, js]
----
Route.get('make/:drink?', ({ params }) => {
  // 未定义 drink 时，使用 Coffee 作为备用
  const drink = params.drink || 'Coffee'

  return `One ${drink}, coming right up!`
})
----

以上示例中，`:drink?` 是一个可选的路由参数。

== 通配路由

你可能希望从服务器呈现单个视图，并使用你喜欢的前端框架处理路由：

.start/routes.js
[source, js]
----
Route.any('*', ({ view }) => view.render('...'))
----

任何特定的路由都需要在通配路由之前定义：

.start/routes.js
[source, js]
----
Route.get('api/v1/users', closure)

Route.any('*', ({ view }) => view.render('...'))
----

== 命名路由

虽然路由是在 `start/routes.js` 文件中定义的，但它们在应用程序中的其他位置都被引用（例如，使用 `views` 路由助手为给定路由创建 URL）。

通过使用该 `as()` 方法，你可以为路由指定唯一名称：

.start/routes.js
[source, js]
----
Route.get('users', closure).as('users.index')
----

这将使你能够在模板和代码中使用 `route` 助手，如下所示：

[source, html]
----
<!-- 之前 -->
<a href="/users">List of users</a>

<!-- 之后 -->
<a href="{{ route('users.index') }}">List of users</a>
----

[source, js]
----
foo ({ response }) {
  return response.route('users.index')
}
----

两个 `route` 助手共享相同的签名，并接受一个可选的参数对象作为第二个参数：

[source, js]
----
Route.get('posts/:id', closure).as('posts.show')

route('posts.show', { id: 1 })
----

`route` 助手还可以接受一个可选的参数对象作为第三个参数，它将处理 `protocol`, `domain` 和 `query` 选项：

[source, js]
----
route('posts.show', { id: 1 }, {
  query: { foo: 'bar' }
});

// 产生 /post/1?foo=bar

// 没有参数：
route('auth.login', null, {
  domain: 'auth.example.com',
  protocol: 'https',
  query: { redirect: '/dashboard' }
});

// 产生 https://auth.example.com/login?redirect=%2Fdashboard
----

这些规则也适用于视图。

[source, html]
----
<a href="{{ route('posts.show', { id: 1 }, {query: { foo: 'bar' }}) }}">Show post</a>
// href="/post/1?foo=bar"
----

== 路由格式

路由格式为 link:https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation[content negotiation, window="_blank"] 开辟了一种新的方式，你可以在其中接受响应格式作为 URL 的一部分。

路由格式是客户端和服务器之间为返回哪种类型的响应而签订的协定：

.start/routes.js
[source, js]
----
Route.get('users', async ({ request, view }) => {
  const users = await User.all()

  if (request.format() === 'json') {
    return users
  }

  return view.render('users.index', { users })
}).formats(['json'])
----

对于以上示例， `/users` 端点将能够基于 URL 以多种格式进行响应：

[source, bash]
----
GET /users.json     # Returns an array of users in JSON
GET /users          # Returns the view in HTML
----

你还可以禁用默认 URL 并强制客户端定义格式：

.start/routes.js
[source, js]
----
Route.get('users', closure).formats(['json', 'html'], true)
----

将 `true` 作为第二个参数传递可以确保客户端指定一种预期格式。否则，抛出一个 404 错误。

== 路由资源

你通常会创建资源路由来对资源执行 CRUD 操作。

`Route.resource` 使用单行代码将 CRUD 路由分配给控制器：

.start/routes.js
[source, js]
----
// 这个...
Route.resource('users', 'UserController')

// ...等同于:
Route.get('users', 'UserController.index').as('users.index')
Route.post('users', 'UserController.store').as('users.store')
Route.get('users/create', 'UserController.create').as('users.create')
Route.get('users/:id', 'UserController.show').as('users.show')
Route.put('users/:id', 'UserController.update').as('users.update')
Route.patch('users/:id', 'UserController.update')
Route.get('users/:id/edit', 'UserController.edit').as('users.edit')
Route.delete('users/:id', 'UserController.destroy').as('users.destroy')
----

NOTE: 此功能仅在将路由绑定到 link:controllers[Controller] 时可用。

你还可以定义资源嵌套：

.start/routes.js
[source, js]
----
Route.resource('posts.comments', 'PostCommentController')
----

=== 资源过滤

你可以通过连缀下面的某个筛选方法来限制 `Route.resource` 方法分配的路由。

==== apiOnly

移除 `GET resource/create` and `GET resource/:id/edit` 路由：

.start/routes.js
[source, js]
----
Route.resource('users', 'UserController')
  .apiOnly()
----

==== only

仅保留指定的路由：

.start/routes.js
[source, js]
----
Route.resource('users', 'UserController')
  .only(['index', 'show'])
----

==== except

保留指定路由之外的所有路由：

.start/routes.js
[source, js]
----
Route.resource('users', 'UserController')
  .except(['index', 'show'])
----

=== 资源中间件

你可以像使用单个路由一样将中间件附加到资源路由：

.start/routes.js
[source, js]
----
Route.resource('users', 'UserController')
  .middleware(['auth'])
----

如果你不想将中间件附加到通过 `Route.resource` 生成的所有路由，你可以通过传递 `Map` 给 `middleware` 方法来自定义此行为：

.start/routes.js
[source, js]
----
Route.resource('users', 'UserController')
  .middleware(new Map([
    [['store', 'update', 'destroy'], ['auth']]
  ]))
----

以上示例最后你，auth 中间件仅应用于存储、更新和销毁路由

=== 资源格式

你可以通过 formats 方法为资源路由定义响应格式：

.start/routes.js
[source, js]
----
Route.resource('users', 'UserController')
  .formats(['json'])
----

== 路由域

你的应用程序可能使用多个域。

AdonisJs 可以轻易的处理此用例。

域可以是静态端点 `blog.adonisjs.com`，也可以是动态端点 `:user.adonisjs.com`。

NOTE: 你也可以在单个路由上定义域。

.start/routes.js
[source, js]
----
Route.group(() => {
  Route.get('/', ({ subdomains }) => {
    return `The username is ${subdomains.user}`
  })
}).domain(':user.myapp.com')
----

以上示例中，如果你访问 `virk.myapp.com`，你将会看到 `The username is virk`。

== 路由组

如果你的路由共享公共逻辑/配置，则你可以这样对它们分组，而不需要为每个路由重新配置：

.start/routes.js
[source, js]
----
// 未分组
Route.get('api/v1/users', closure)
Route.post('api/v1/users', closure)

// 已分组
Route.group(() => {
  Route.get('users', closure)
  Route.post('users', closure)
}).prefix('api/v1')
----

=== 前缀

为组中定义的所有路由 URL 添加前缀：

.start/routes.js
[source, js]
----
Route.group(() => {
  Route.get('users', closure)   // GET /api/v1/users
  Route.post('users', closure)  // POST /api/v1/users
}).prefix('api/v1')
----

=== 中间件

将一个或多个中间件分配给路由组：

.start/routes.js
[source, js]
----
Route.group(() => {
  //
}).middleware(['auth'])
----

NOTE: 组中间件在路由中间件之前执行。

=== 命名空间

为绑定控制器的名称空间添加前缀：

.start/routes.js
[source, js]
----
Route.group(() => {
  // 将 '/users' 绑定到 'App/Controllers/Http/Admin/UserController'
  Route.resource('/users', 'UserController')
}).namespace('Admin')
----

=== 格式

定义组内所有路由的格式：

.start/routes.js
[source, js]
----
Route.group(() => {
  //
}).formats(['json', 'html'], true)
----

=== 域名

指定哪个路由组属于哪个域：
Specify which domain group routes belong to:

.start/routes.js
[source, js]
----
Route.group(() => {
  //
}).domain('blog.adonisjs.com')
----
