---
title: 中间件
category: 基础
permalink: middleware
---

= 中间件

toc::[]

中间件挂钩到应用程序的请求生命周期。

它们是按顺序执行的一组函数，允许你转换请求或响应。

例如， AdonisJs 提供了一个 `auth` 中间件，用于验证应用程序的用户是否经过身份验证。如果用户未经过身份验证，则会抛出异常，并且请求永远不会到达你的路由处理程序。

== 创建中间件

要创建新的中间件，请使用 `make:middleware` 命令：

[source, bash]
----
> adonis make:middleware CountryDetector
----

该命令将在 `app/Middleware` 文件夹中创建一个带有一些样板代码的文件。

在我们的示例 `CountryDetector` 中间件中，我们希望通过用户的 IP 地址检到用户的国家/地区：

.app/Middleware/CountryDetector.js
[source, js]
----
'use strict'

const geoip = require('geoip-lite')

class CountryDetector {
  async handle ({ request }, next) {
    const ip = request.ip()
    request.country = geoip.lookup(ip).country
    await next()
  }
}

module.exports = CountryDetector
----

在该示例中，我们使用 `geoip-lite` 库将用户所在国家/地区添加到 link:request-lifecycle#_http_context[HTTP Context] 的 `request` 对象中。

=== 上游和下游中间件

创建中间件时，你需要确定它是在请求到达路由处理程序之前还是之后运行。

以下是通过中间件 `handle` 方法的 `await next()` 调用前后顺序来完成的：

.app/Middleware/UpstreamExample.js
[source, js]
----
'use strict'

class UpstreamExample {
  async handle ({ request }, next) {
    // Code...
    await next()
  }
}

module.exports = UpstreamExample
----

要访问下游中间件的 `response` 对象，你需要从传递过来的 link:request-lifecycle#_http_context[HTTP Context] 中解构它：

.app/Middleware/DownstreamExample.js
[source, js]
----
'use strict'

class DownstreamExample {
  async handle ({ response }, next) {
    await next()
    // Code...
  }
}

module.exports = DownstreamExample
----

如果需要，你的中间件代码也可以在请求到达路由处理程序之前 **和** 和之后运行：

.app/Middleware/BeforeAndAfterExample.js
[source, js]
----
'use strict'

class BeforeAndAfterExample {
  async handle ({ response }, next) {
    // 上游代码...
    await next()
    // 下游代码...
  }
}

module.exports = BeforeAndAfterExample
----

== 注册中间件

所有中间件都在 `start/kernel.js` 文件中注册。

中间件分为三类： **服务器中间件**, **全局中间件** 和 **命名中间件**。

=== 服务器中间件

服务器中间件在请求到达 AdonisJs 路由系统之前执行。这意味着如果请求的路由未注册， AdonisJs 仍将执行此处定义的所有中间件：

.start/kernel.js
[source, js]
----
const serverMiddleware = [
  'Adonis/Middleware/Static',
  'Adonis/Middleware/Cors',
]
----

服务器中间件通常用于服务于静态资源或处理 CORS。

=== 全局中间件

找到请求的路由后，将会执行全局中间件：

.start/kernel.js
[source, js]
----
const globalMiddleware = [
  'Adonis/Middleware/BodyParser',
]
----

全局中间件按照定义的顺序执行，因此当一个中间件需要另一个中间件时必须小心。

=== 命名中间件

命名中间件被分配给特定路由或路由组：

.start/kernel.js
[source, js]
----
const namedMiddleware = {
  auth: 'Adonis/Middleware/Auth',
}
----

.start/routes.js
[source, js]
----
Route.get(url, closure).middleware(['auth'])
----

命名的中间件按其分配的路由定义的顺序执行。

== 中间件属性

AdonisJs 使用 link:https://www.npmjs.com/package/haye#pipe-expression[pipe expression, window="_blank"] 来定义中间件属性。

例如，`auth` 中间件可以选择不同的身份认证方案作为中间件属性：

.start/routes.js
[source, js]
----
// 在这个路由上使用 Session 方案
Route.post(url, closure).middleware(['auth:session'])

// 在这个路由上使用 JWT 方案
Route.post(url, closure).middleware(['auth:jwt'])
----

你可以通过逗号链接它们来使用多个方案：

.start/routes.js
[source, js]
----
Route.post(url, closure).middleware(['auth:session,jwt'])
----

这些属性可用作中间件 `handle` 方法中的第三个参数：

[source, js]
----
async handle (context, next, properties) {
  //
}
----
