---
permalink: request
title: 请求
category: 基础
---

= 请求

toc::[]

本指南概述了如何使用 link:https://github.com/adonisjs/adonis-framework/blob/develop/src/Request/index.js[HTTP Request, window="_blank"] 对象读取请求数据。

TIP: 可以通过 `request.request` 访问 Node.js 的原始 `req` 对象。

AdonisJs 将当前的 HTTP 请求对象作 link:request-lifecycle#_http_context[HTTP Context] 的一部分传递给所有路由处理程序和中间件：

[source, js]
----
Route.get('/', ({ request }) => {
  //
})
----

以上示例中，我们使用 link:https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment[ES6 解构, window="_blank"] 从 HTTP context 对象中获取到的 `request` 对象。

== 请求主体
请求对象提供了许多有用的方法来读取请求主体。

首先，确保你已经安装了 **BodyParser** 中间件。

如果没有，请执行以下步骤：

=== 设置 BodyParser
NOTE: Fullstack 和 API only boilerplates 已经预先配置了 BodyParser 中间件。

运行 BodyParser 安装命令：
[source, bash]
----
> adonis install @adonisjs/bodyparser
----

然后，在 `start/app.js` 文件中注册提供者：

.start/app.js
[source, js]
----
const providers = [
  '@adonisjs/bodyparser/providers/BodyParserProvider'
]
----

最后，在 `start/kernel.js` 文件最后你注册全局中间件：

.start/kernel.js
[source, js]
----
const globalMiddleware = [
  'Adonis/Middleware/BodyParser'
]
----

=== 主体方法
以下方法列表可用于读取请求主体。

==== all
返回包含所有请求数据的对象（合并查询参数和请求主体数据，即 get 和 post）：

[source, js]
----
const all = request.all()
----

==== get
返回一个包含 get 查询参数数据的对象：

[source, js]
----
const query = request.get()
----

==== post
返回一个包含 post 请求主体数据的对象：

[source, js]
----
const body = request.post()
----

==== raw
以字符串形式返回原始主体数据：

[source, js]
----
const raw = request.raw()
----

NOTE: 如果原始数据是 JSON 且设置了 `Content-type: application/json`， BodyParser 将自动对其解析，并将其作为 `post` 方法的一部分返回。

==== only
返回仅包含指定键的对象：

[source, js]
----
const data = request.only(['username', 'email', 'age'])
----

==== except
返回除指定键以外的所有对象（与 only 相反）：

[source, js]
----
const data = request.except(['csrf_token', 'submit'])
----

==== input
获取给定键的值（如果它不存在，则返回 `默认` 值）：

[source, js]
----
const drink = request.input('drink')

// 具有默认值
const drink = request.input('drink', 'coffee')
----


== 请求集合
通常，你可能希望处理通过键/值对提交数据数组的 HTML 表单。

例如，以下表单一次创建多个用户：

[source, html]
----
<form method="POST" action="/users">

  <input type="text" name="username[0]" />
  <input type="text" name="age[0]" />

  <input type="text" name="username[1]" />
  <input type="text" name="age[1]" />

</form>
----

假设我们要在控制器中获取用户名和年龄：

[source, js]
----
const users = request.only(['username', 'age'])

// output
{ username: ['virk', 'nikk'], age: [26, 25] }
----

以上示例格式不正确，因此无法保存到数据库。

我们可以使用 `request.collect` 格式化它，以便它可以保存到数据库：

[source, js]
----
const users = request.collect(['username', 'age'])

// 输出
[{ username: 'virk', age: 26 }, { username: 'nikk', age: 25 }]

// 保存到数据库
await User.createMany(users)
----

== 信息头
你可以使用以下任一方法从请求中读取信息头（Headers）。

==== header
给定键的 header 值（可选使用默认值）：

[source, js]
----
var auth = request.header('authorization')

// 不区分大小写
var auth = request.header('Authorization')

// 带默认值
const other = request.header('some-other-header', 'default')
----

==== headers
返回所有 header 数据的对象：

[source, js]
----
const headers = request.headers()
----

== Cookies
你可以使用以下任一方法从请求中读取 Cookies。

==== cookie
给定键的 cookie 值（可选使用默认值）：

[source, js]
----
const cartTotal = request.cookie('cart_total')

// 带默认值
const cartTotal = request.cookie('cart_total', 0)
----

==== cookies
返回所有 cookie 数据的对象：

[source, js]
----
const cookies = request.cookies()
----

以下方法用于读取客户端设置的 cookies。

==== plainCookie
给定键的原始 cookie 值(可选择使用默认值)：
[source, js]
----
const jsCookie = request.plainCookie('cart_total')

// 带默认值
const jsCookie = request.plainCookie('cart_total', 0)
----

==== plainCookies
返回所有原始 cookie 数据的对象：
[source, js]
----
const plainCookies = request.plainCookies()
----

== 内容协商

link:https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation[内容协商, window="_blank"] 是服务器和客户端约定从服务器返回的最佳响应类型的一种方式。

Web 服务器不仅为 web 页面提供服务 - 它们还必须处理以 *JSON*， *XML* 等形式提供的 API 响应。

使用者可以要求服务器以特定格式返回响应，而不是为每种内容类型创建单独的URL。

要以特定格式构造响应，服务器首先需要知道请求的格式。这可以使用 `accepts` 方法完成。

==== accepts
读取 `Accept` 标题以帮助确定响应格式：

[source, js]
----
const bestFormat = request.accepts(['json', 'html'])

if (bestFormat === 'json') {
  return response.json(users)
}

return view.render('users.list', { users })
----

==== language
语言也可以根据 `Accept-Language` 标题进行协商：

[source, js]
----
const language = request.language(['en', 'fr'])
----

== 请求方法
下面是所有请求方法及其示例用法的列表。

==== url
返回当前请求的URL：

[source, js]
----
const url = request.url()
----

==== originalUrl
返回当前包含查询字符串的完整的请求 url：

[source, js]
----
const url = request.originalUrl()
----

==== method
返回 HTTP 的请求方法：

[source, js]
----
const method = request.method()
----

==== intended
由于 AdonisJs 允许 xref:_方法欺骗[方法欺骗]，你可以使用 `intended` 方法获取实际方法：

[source, js]
----
const method = request.intended()
----

==== ip
返回用户最信任的 ip 地址：

[source, js]
----
const ip = request.ip()
----

==== ips
返回最信任到最不信任的 ips 数组（删除了默认的 ip 地址，可以通过 `ip` 方法访问）：

[source, js]
----
const ips = request.ips()
----

==== subdomains
返回请求子域列表（列表中删除了 `www`）：

[source, js]
----
const subdomains = request.subdomains()
----

==== ajax
检查 `X-Requested-With` 头，以确认请求是否为 ajax：

[source, js]
----
if (request.ajax()) {
  // do something
}
----

==== pjax
link:https://github.com/defunkt/jquery-pjax[Pjax, window="_blank"] 是一种使用 Ajax 为传统应用程序提供更好用户体验的演进方式。在 Rails 世界中，它被称为 Turbolinks。

该方法通过查找 `X-PJAX` 头来标识请求是否为 pjax：
[source, js]
----
if (request.pjax()) {
  // do something
}
----

==== hostname
返回请求主机名：

[source, js]
----
const hostname = request.hostname()
----

==== protocol
返回请求协议：

[source, js]
----
const protocol = request.protocol()
----

==== match
返回传递的表达式集是否与当前请求 URL 匹配：

[source, js]
----
// 当前请求 url - posts/1

request.match(['posts/:id']) // 返回 true
----

==== hasBody
一个判断请求是否有 post 主体的布尔值（主要由 BodyParser 用于确定是否解析主体）:

[source, js]
----
if (request.hasBody()) {
  // do something
}
----

==== is
`is` 用于返回当前请求的最佳匹配内容类型。

该检查完全基于 `content-type` 头：

[source, js]
----
// 假设 content-type 是 `application/json`

request.is(['json', 'html']) // 返回 - json

request.is(['application/*']) // 返回 - application/json
----

== 方法欺骗
HTML 表单只能发送 `GET` 和 `POST` 请求，这意味着你无法使用其他 HTTP 方法的 REST 约定，例如 `PUT`， `DELETE` 等等。

AdonisJs通过在查询字符串中添加一个 `_method` 参数，自动为你执行正确的路由，从而轻松的绕过请求方法：

.start/routes.js
[source, js]
----
Route.put('users', 'UserController.update')
----

[source, html]
----
<form method="POST" action="/users?_method=PUT">
----

上述示例适用于以下情况：

1. 原始请求方法是 `POST`.
2. 在 `config/app.js` 文件中启用了 `allowMethodSpoofing`。

== 扩展请求
还可以通过添加自己的方法来扩展 `请求` 原型，称为宏。

NOTE: 由于扩展 `请求` 的代码仅需执行一次，因此你可以使用 link:service-providers[服务提供者] 或 link:ignitor[启动装置的钩子] 来执行。请阅读 link:extending-adonisjs[核心扩展] 了解更多信息。

[source, javascript]
----
const Request = use('Adonis/Src/Request')

Request.macro('cartValue', function () {
  return this.cookie('cartValue', 0)
})
----
