---
permalink: response
title: 响应
category: 基础
---

= 响应

toc::[]

本指南概述了如何使用 link:https://github.com/adonisjs/adonis-framework/blob/develop/src/Response/index.js[HTTP Response, window="_blank"] 来生成和返回响应。

TIP: 可以通过 `response.response` 访问 Node.js 的原始 `req` 对象。

AdonisJs 将当前的 HTTP 响应对象作为 link:request-lifecycle#_http_context[HTTP Context] 的一部分传递给所有路由处理程序和中间件：

.start/routes.js
[source, js]
----
Route.get('/', ({ response }) => {
  response.send('hello world')
})
----

== 基本例子
以下示例以 JSON 格式返回用户数组：

.start/routes.js
[source, js]
----
Route.get('/users', async ({ response }) => {
  const users = await User.all()
  response.send(users)
})
----

`response.json` 方法也可用作 `response.send` 的别名：

.start/routes.js
[source, js]
----
Route.get('/users', async ({ response }) => {
  response.json(await User.all())
})
----

== 做出响应
从 4.0 开始，你可以在路由的闭包或控制器方法中直接 `返回` 值，而不是使用专用的 `response` 方法。

以下内容等同于 `response.send` 或 `response.json`，但使用简单的 return 语句感觉更自然：

.start/routes.js
[source, js]
----
Route.get('/', async () => {
  return await User.all()
})
----

=== 避免回调
由于请求/响应声明周期允许你返回值或调用专用的响应方法，因此 AdonisJs 完全不鼓励使用回调。

在回调中发送的以下响应将不起作用：

.start/routes.js
[source, js]
----
Route.get('/', async ({ response }) => {
  fs.readFile('somefile', (error, contents) => {
    response.send(contents)
  })
})
----

上述代码无法工作的原因是，一旦路由处理程序执行，AdonisJs 就会终止响应 - 因为稍后将执行回调，所以会发生错误！

=== Promisify 回调
相反，你可以  **promisify** 式你的回调，并将其与 `await` 一起使用：

.start/routes.js
[source, js]
----
const fs = use('fs')
const Helpers = use('Helpers')
const readFile = Helpers.promisify(fs.readFile)

Route.get('/', async ({ response }) => {
  return await readFile('somefile')
})
----

JavaScript 拥有丰富的生态系统，只需要 **promisify** 式它们就可以 *100% 的* 编写没有回调的代码，作为一个社区，我们鼓励这种方法。

=== 但是… 我喜欢我的回调！
如果你仍然喜欢回调，AdonisJs 提供一种继续使用它们的方法。

只需指示 `response` 对象不要隐式结束即可：

.start/routes.js
[source, js]
----
Route.get('/', async ({ response }) => {
  response.implicitEnd = false

  fs.readFile('somefile', (error, contents) => {
    response.send(contents)
  })
})
----

== 信息头
使用以下方法设置/删除响应头（Headers）。

==== header
设置 header 值：

[source, js]
----
response.header('Content-type', 'application/json')
----

==== safeHeader
仅设置 header 值，如果不存在：

[source, js]
----
response.safeHeader('Content-type', 'application/json')
----

==== removeHeader
删除现有的 header：

[source, js]
----
response.removeHeader('Content-type')
----

==== type
设置 `Content-Type` header:

[source, js]
----
response.type('application/json')
----

== Cookies
使用以下方法设置/删除响应 cookies。

==== cookie
设置 cookie 值：

[source, js]
----
response.cookie('cartTotal', 20)
----

==== clearCookie
删除现有的 cookie（通过将过期时间设为过去）：

[source, js]
----
response.clearCookie('cartTotal')
----

==== plainCookie
由于所有 cookie 都经过加密和签名，因此无法从前端 JavaScript 代码中读取它们。

这种情况下，可能想要设置一个普通的 cookie：

[source, js]
----
// 未签名或加密
response.plainCookie('cartTotal', 20)
----

== 重定向
使用以下方法之一将请求重定向到其他 URL。

==== redirect(url, [sendParams = false], [status = 302])
将请求重定向到其他 url（默认情况下，它将状态设置为 `302`）：

[source, js]
----
response.redirect('/url')

// 或
response.redirect('/url', false, 301)
----

你可以通过将第二个参数设置为 `true` ，将当前请求参数发送到重定向位置：

[source, js]
----
response.redirect('/url', true)
----

==== route(route, [data], [domain], [sendParams = false], [status = 302])
重定向到路由（通过路由名称或控制器方法）：

.start/routes.js
[source, js]
----
Route
  .get('users/:id', 'UserController.show')
  .as('profile')
----

[source, js]
----
// 通过路由名称
response.route('profile', { id: 1 })

// 通过控制器方法
response.route('UserController.show', { id: 1 })
----

由于 AdonisJs 允许为 link:routing#_routing_domains[多个域] 注册路由，因此您还可以指示此方法为特定域构建 URL：

[source, js]
----
response.route('posts', { id: 1 }, 'blog.adonisjs.com')
----

== 附件
response 对象使你可以轻松地将文件从服务器传输到客户端。

==== download(filePath)
将文件以流式传输到客户端：

[source, js]
----
response.download(Helpers.tmpPath('uploads/avatar.jpg'))
----

此方法不强制客户端将文件作为附件下载（例如，浏览器可以选择在新窗口中显示该文件）。

==== attachment(filePath, [name], [disposition])
强制下载文件：

[source, js]
----
response.attachment(
  Helpers.tmpPath('uploads/avatar.jpg')
)
----

使用自定义名称下载：

[source, js]
----
response.attachment(
  Helpers.tmpPath('uploads/avatar.jpg'),
  'myAvatar.jpg' // 自定义名称
)
----

== 描述性方法
AdonisJs 附带了一堆描述性信息，比 `send` 方法更具可读性，让我们举个例子。

[source, javascript]
----
response.unauthorized('Login First')
----

以上代码比以下代码更具可读性：

[source, javascript]
----
response.status(401).send('Login First')
----

以下是所有描述性方法及其 HTTP 状态的对应列表。查看 link:https://httpstatuses.com[httpstatuses.com, window="_blank"] 以了解有关 HTTP 状态码的更多信息。

[options="header"]
|====
| 方法 | HTTP 响应状态
| continue | 100
| switchingProtocols | 101
| ok | 200
| created | 201
| accepted | 202
| nonAuthoritativeInformation | 203
| noContent | 204
| resetContent | 205
| partialContent | 206
| multipleChoices | 300
| movedPermanently | 301
| found | 302
| seeOther | 303
| notModified | 304
| useProxy | 305
| temporaryRedirect | 307
| badRequest | 400
| unauthorized | 401
| paymentRequired | 402
| forbidden | 403
| notFound | 404
| methodNotAllowed | 405
| notAcceptable | 406
| proxyAuthenticationRequired | 407
| requestTimeout | 408
| conflict | 409
| gone | 410
| lengthRequired | 411
| preconditionFailed | 412
| requestEntityTooLarge | 413
| requestUriTooLong | 414
| unsupportedMediaType | 415
| requestedRangeNotSatisfiable | 416
| expectationFailed | 417
| unprocessableEntity | 422
| tooManyRequests | 429
| internalServerError | 500
| notImplemented | 501
| badGateway | 502
| serviceUnavailable | 503
| gatewayTimeout | 504
| httpVersionNotSupported | 505
|====

== 扩展响应
还可以通过添加自己的方法来扩展 `响应` 原型，称为宏。

NOTE: 由于扩展 `响应` 的代码仅需执行一次，因此你可以使用 link:service-providers[服务提供者] 或 link:ignitor[启动装置的钩子] 来执行。请阅读 link:extending-adonisjs[核心扩展] 了解更多信息。

[source, js]
----
const Response = use('Adonis/Src/Response')

Response.macro('sendStatus', function (status) {
  this.status(status).send(status)
})
----
