---
permalink: sessions
title: Sessions
category: 基础
---

= Sessions

toc::[]

AdonisJs 具备一流的 session 支持，并提供各种内置驱动程序来高效的管理和存储 sessions。

在本指南中，我们将学习如何配置和使用这些不同的 session 驱动程序。

== 设置
如果尚未设置 session 提供者，请按照以下说明进行操作：

首先，运行 `adonis` 命令下载 session 提供者：

[source, bash]
----
> adonis install @adonisjs/session
----

以上命令还会创建 `config/session.js` 文件，并显示一小部分说明来帮助你完成设置。

接下来，在 `start/app.js` 文件中注册 session 提供者：

.start/app.js
[source, js]
----
const providers = [
  '@adonisjs/session/providers/SessionProvider'
]
----

最后，在 `start/kernel.js` 文件中注册 session 中间件：

.start/kernel.js
[source, js]
----
const globalMiddleware = [
  'Adonis/Middleware/Session'
]
----

== 支持的驱动程序
以下是 session 提供者支持的驱动程序列表。你可以在 `config/session.js` 文件中更改当前驱动程序。

NOTE: Redis 驱动程序需要 `@adonisjs/redis` 程序包 (相关安装说明，请参阅 link:redis[Redis] 章节)。

[options="header", cols="10, 20, 70"]
|====
| 名称 | 配置键 | 描述
| Cookie | cookie | 将 session 值保存到加密的 cookies 中。
| File | file | 将 session 值保存在服务器上的文件中（如果在多个服务器上和负载均衡器上运行AdonisJs，则不应使用此选项）。
| Redis | redis | 保存到 link:https://redis.io[Redis, window="_blank"] 中（适合水平缩放）。
|====

== 基本例子
`session` 对象作为 link:request-lifecycle#_http_context[HTTP Context] 的一部分传递，如同 `request` 和 `response` 对象。

以下是如何在 HTTP 生命周期中使用 session 的快速示例：

.start/routes.js
[source, js]
----
Route.get('/', ({ session, response }) => {
  session.put('username', 'virk')
  response.redirect('/username')
})

Route.get('/username', ({ session }) => {
  return session.get('username') // 'virk'
})
----

== Session 方法
以下是所有 session 方法及其示例用法的列表。

==== put(key, value)
将键值对添加到 session 存储：

[source, js]
----
session.put('username', 'virk')
----

==== get(key, [defaultValue])
返回给定键的值(接收可选的默认值)：

[source, js]
----
session.get('username')

// 默认值
session.get('username', 'defaultName')
----

==== all
将 session 存储中的所有内容作为对象返回：

[source, js]
----
session.all()
----

==== increment(key, [steps])
增加给定键的值(确保前一个值是一个数字)：

[source, js]
----
session.increment('counter')

// 增加5
session.increment('counter', 5)
----

==== decrement(key, [steps])
减小给定键的值(确保前一个值是一个数字)：

[source, js]
----
session.decrement('counter')

// 减去2
session.decrement('counter', 2)
----

==== forget(key)
从 session 存储中删除键值对：
[source, js]
----
session.forget('username')
----

==== pull(key, [defaultValue])
从 session 存储中返回(然后删除)键值对：

[source, js]
----
const username = session.pull('username') // returns username

session.get('username') // null
----

==== clear
清空 session 存储：

[source, js]
----
session.clear()
----

== Flash（闪存）消息
Flash 消息是仅仅针对单个请求的 session 值。它主要用于 *闪存错误信息*，但也可以用于任何其他目的。

=== HTML 表单示例

假设我们想要验证提交的用户数据，并在存在验证错误时重定向回我们的表单。

从以下HTML表单开始：

[source, edge]
----
<form method="POST" action="/users">
  {{ csrfField() }}
  <input type="text" name="username" />
  <button type="submit">Submit</button>
</form>
----

然后，注册 `/users` 路由以验证表单数据：

.app/routes.js
[source, js]
----
const { validate } = use('Validator')

Route.post('users', ({ request, session, response }) => {
  const rules = { username: 'required' }
  const validation = await validate(request.all(), rules)

  if (validation.fails()) {
    session.withErrors(validation.messages()).flashAll()
    return response.redirect('back')
  }

  return 'Validation passed'
})
----

最后，重写 HTML 表单以使用 link:sessions#_view_helpers[视图助手] 检索 Flash 数据：

[source, edge]
----
<form method="POST" action="/users">
  {{ csrfField() }}
  <input type="text" name="username" value="{{ old('username', '') }}" />
  {{ getErrorFor('username') }}
  <button type="submit">Submit</button>
</form>
----

=== Flash 方法
以下是所有 session Flash 方法及其示例用法的列表。

==== flashAll
闪存请求表单数据：

[source, js]
----
session.flashAll()
----

==== flashOnly
仅闪存选定的字段：

[source, js]
----
session.flashOnly(['username', 'email'])
----

==== flashExcept
闪存除选定字段之外的请求表单数据：

[source, js]
----
session.flashExcept(['password', 'csrf_token'])
----

==== withErrors
闪存出现一系列错误：

[source, js]
----
session
  .withErrors([{ field: 'username', message: 'Error message' }])
  .flashAll()
----

==== flash
闪存一个自定义对象：

[source, js]
----
session.flash({ notification: 'You have been redirected back' })
----

=== 视图助手
使用 Flash 消息时，可以使用以下视图助手从 Flash session 存储中读取值。

==== old(key, defaultValue)
从 flash 存储返回给定键的值：

[source, js]
----
session.flashOnly(['username'])
----

[source, edge]
----
<input type="text" name="username" value="{{ old('username', '') }}" />
----

==== hasErrorFor(key)
如果 flash 存储中的给定字段存在错误，则返回 `true`：

[source, js]
----
session
  .withErrors({ username: 'Username is required' })
  .flashAll()
----

[source, edge]
----
@if(hasErrorFor('username'))
  // 显示错误
@endif
----

==== getErrorFor(key)
返回给定字段的错误消息：

[source, js]
----
session
  .withErrors({ username: 'Username is required' })
  .flashAll()
----

==== flashMessage(key, defaultValue)
返回给定键的 flash 消息：

[source, js]
----
session.flash({ notification: 'Update successful!' })
----

[source, edge]
----
@if(flashMessage('notification'))
  <span>{{ flashMessage('notification') }}</span>
@endif
----

== Session 持久化
当请求结束时，session 值将会批量保存。这样可以保持 请求/响应 的性能，因为你可以根据需要多次更改 session 存储，并且仅在最后执行批量更新。

它是通过 AdonisJs 中间件实现的（参见 link:https://github.com/adonisjs/adonis-session/blob/develop/src/Session/Middleware.js#L89[此处, window="_blank"]）。

但是，一旦抛出异常，则中间件层将中断，并且永远不会提交 session 值。

AdonisJs 的官方软件（第一方）包可以很好的处理此问题，但如果想要处理自己的异常，则应手动提交 session：

[source, js]
----
const GE = require('@adonisjs/generic-exceptions')

class MyCustomException extends GE.LogicalException {
  handle (error, { session }) {
    await session.commit()
    // 异常处理
  }
}
----
