---
title: 验证器
permalink: validator
category: 基础
---

= 验证器

toc::[]

通过 AdonisJs，可以借助验证器提供者轻松地验证用户输入。

在本指南中，你将学习如何 *手动* 或者通过 *路由验证器* 验证数据。

NOTE: AdonisJs 验证引擎使用的是 link:http://indicative.adonisjs.com[Indicative, window="_blank"]，有关详细使用说明，请参阅官方指示 link:http://indicative.adonisjs.com[文档].

== 设置
按照以下说明设置验证提供者。

首先，运行 `adonis` 命令以下载验证提供者：

[source, bash]
----
> adonis install @adonisjs/validator
----

然后，在 `start/app.js` 文件中注册验证提供者：

.start/app.js
[source, js]
----
const providers = [
  '@adonisjs/validator/providers/ValidatorProvider'
]
----

== 验证用户输入
让我们从验证通过HTML形式接收的用户输入的示例开始：

[source, html]
----
<form method="POST" action="{{ route('UserController.store') }}">
  <div>
    <input type="text" name="email" />
  </div>

  <div>
    <input type="text" name="password" />
  </div>

  <button type="submit"> Submit </button>
</form>
----

注册路由和控制器以处理表单提交，并使用验证器验证数据：

.start/routes.js
[source, js]
----
Route.post('users', 'UserController.store')
----

[source, js]
----
const { validate } = use('Validator')

class UserController {

  async store ({ request, session, response }) {
    const rules = {
      email: 'required|email|unique:users,email',
      password: 'required'
    }

    const validation = await validate(request.all(), rules)

    if (validation.fails()) {
      session
        .withErrors(validation.messages())
        .flashExcept(['password'])

      return response.redirect('back')
    }

    return 'Validation passed'
  }
}

module.exports = UserController
----

让我们将上面的控制器代码分解为几个小步骤：

1. 我们定义了我们 `rules` 规则模式。
2. 我们使用了 `validate` 方法根据我们的规则验证所有的请求数据。
3. 如果验证失败，我们将刷新所有错误并重定向回表单。

=== 显示闪存错误
我们可以修改HTML表单以显示验证失败时设置的flash消息：

[source, edge]
----
<form method="POST" action="{{ route('UserController.store') }}">
  <div>
    <input type="text" name="email" value="{{ old('email', '') }}" />
    {{ elIf('<span>$self</span>', getErrorFor('email'), hasErrorFor('email')) }}
  </div>

  <div>
    <input type="text" name="password" />
    {{ elIf('<span>$self</span>', getErrorFor('password'), hasErrorFor('password')) }}
  </div>

  <button type="submit"> Submit </button>
</form>
----

== 验证方法
以下是可用方法列表。

==== validate(data, rules, [messages], [formatter])
使用定义的规则验证数据：

[source, js]
----
const { validate } = use('Validator')

const validation = await validate(data, rules)

if (validation.fails()) {
  return validation.messages()
}
----

NOTE: 你可以选择传递 link:http://indicative.adonisjs.com/docs/custom-messages[自定义错误消息, window="_blank"]，以在验证失败时作为第三个方法参数返回。

==== validateAll(data, rules, [messages], [formatter])
与 `validate` 相同，但是继续验证所有字段，而 `validate` 方法则在出现第一个错误时停止：

[source, js]
----
const { validateAll } = use('Validator')
const validation = await validateAll(data, rules)
----

==== sanitize(data, rules)
该方法返回一个通过验证的包含过滤数据的新对象：

[source, js]
----
const { sanitize } = use('Validator')
const data = sanitize(request.all(), rules)
----

==== sanitizor
返回一个对 Indicative 的 link:http://indicative.adonisjs.com/docs/api/extend#_adding_sanitization_rules[sanitizor, window="_blank"] 的引用：

[source, js]
----
const { sanitizor } = use('Validator')
const slug = sanitizor.slug('My first blog post')
----

==== formatters
返回一个对 Indicative 的 link:http://indicative.adonisjs.com/docs/formatters[formatters, window="_blank"] 的引用：

[source, js]
----
const { formatters } = use('Validator')
validate(data, rules, messages, formatters.JsonApi)
----

== 路由验证
数据验证通常发生在 HTTP 请求和响应生命周期中，最终您可以在每个控制器内编写相同的验证代码。

AdonisJs **路由验证器** 可以使这些重复的验证过程变得更加简单：

[source, js]
----
// 对于普通路由
Route
  .post('users', 'UserController.store')
  .validator('StoreUser')

// 对于资源路由
Route
  .resource('users', 'UserController')
  .validator(new Map([
    [['users.store'], ['StoreUser']],
    [['users.update'], ['UpdateUser']]
  ]))
----

NOTE: 验证器位于 `app/Validators` 目录中。

让我们使用 `adonis` 命令创建一个 `StoreUser` 验证器：

[source, bash]
----
> adonis make:validator StoreUser
----

.make:validator output
[source, bash]
----
create: app/Validators/StoreUser.js
----

现在，我们需要做的就是在验证器上定义我们的规则：

.app/Validators/StoreUser.js
[source, js]
----
'use strict'

class StoreUser {
  get rules () {
    return {
      email: 'required|email|unique:users',
      password: 'required'
    }
  }
}

module.exports = StoreUser
----

如果验证失败，验证器会自动将错误设置为闪存消息，并将用户重定向回表单。

NOTE: 如果请求带有 `Accept: application/json` 头，则响应将作为 JSON 返回。

=== 自定义错误信息
默认错误消息可能会让最终用户感到困惑，因此你可能需要创建自己的自定义验证错误消息。

AdonisJs 提供了一些轻松的方式类实现。

只需在路由验证器上声明一个 `messages` 方法，然后根据规则返回一个包含信息的对象，如下所示：

.app/Validators/StoreUser.js
[source, js]
----
'use strict'

class StoreUser {
  get rules () {
    return {
      email: 'required|email|unique:users',
      password: 'required'
    }
  }

  get messages () {
    return {
      'email.required': 'You must provide a email address.',
      'email.email': 'You must provide a valid email address.',
      'email.unique': 'This email is already registered.',
      'password.required': 'You must provide a password'
    }
  }
}

module.exports = StoreUser
----

=== 验证所有
要验证所有字段，请在类的原型上将 `validateAll` 设置为 true：

.app/Validators/StoreUser.js
[source, js]
----
'use strict'

class StoreUser {
  get validateAll () {
    return true
  }
}

module.exports = StoreUser
----

=== 清除用户输入
你可以通过定义 `sanitizationRules` 在验证发生之前对请求数据执行清理操作，将验证数据清理为你想要的格式：

.app/Validators/StoreUser.js
[source, js]
----
class StoreUser {
  get sanitizationRules () {
    return {
      email: 'normalize_email',
      age: 'to_int'
    }
  }
}

module.exports = StoreUser
----

=== 处理验证失败
由于每个应用程序的结构都不同，因此有时可能不希望自动处理错误。

你可以通过向验证器添加 `fails` 方法来手动处理失败：

.app/Validators/StoreUser.js
[source, js]
----
class StoreUser {
  async fails (errorMessages) {
    return this.ctx.response.send(errorMessages)
  }
}

module.exports = StoreUser
----

=== 自定义数据对象
你可能希望验证不属于请求主体的自定义属性（例如，信息头）。

这可以通过在你的验证器类上定义 `数据` 属性来完成：

.app/Validators/StoreUser.js
[source, js]
----
class StoreUser {
  get rules () {
    return {
      sessionId: 'required'
    }
  }

  get data () {
    const requestBody = this.ctx.request.all()
    const sessionId = this.ctx.request.header('X-Session-Id')

    return Object.assign({}, requestBody, { sessionId })
  }
}

module.exports = StoreUser
----

=== 格式化
你还可以将 link:http://indicative.adonisjs.com/docs/formatters#_available_formatters[Indicative formatter, window="_blank"] 定义为 validator 类的属性：

[source, js]
----
const { formatters } = use('Validator')

class StoreUser {
  get formatter () {
    return formatters.JsonApi
  }
}
----

=== 授权
您可能需要执行检查以确保用户有权执行所需的操作。

这可以通过在你的验证器类上定义一个 `authorize` 方法来完成：

[source, js]
----
class StoreUser {
  async authorize () {
    if (!isAdmin) {
      this.ctx.response.unauthorized('Not authorized')
      return false
    }

    return true
  }
}

module.exports = StoreUser
----

NOTE: 从 `authorize` 方法返回一个 `boolean` 值，告诉验证器是否将请求转发给控制器。

=== 请求上下文（Request context）
所有路由验证器都可以通过 `this.ctx` 访问当前请求上下文。

== 自定义规则
AdonisJs 支持所有 link:https://indicative.adonisjs.com[Indicative] 验证，但也添加了一些自定义规则。

一下是 AdonisJs 自定义规则的列表。

==== unique(tableName, [fieldName], [ignoreField], [ignoreValue])
确保给定值对于给定的数据库表是唯一的：

[source, js]
----
'use strict'

class StoreUser {
  get rules () {
    return {
      email: 'unique:users,email'
    }
  }
}
----

在更新现有用户配置文件时，在执行 `unique` 规则时无需检查其电子邮件地址。这可以通过定义 `ignoreField (id)` 和 `ignoreValue (userId)` 来完成：

[source, js]
----
class StoreUser {
  get rules () {
    const userId = this.ctx.params.id

    return {
      email: `unique:users,email,id,${userId}`
    }
  }
}
----

== 扩展验证器
作为如何扩增 AdonisJs `Validator` 的示例，让我们添加一条新规则，以确保在向数据库添加新 *帖子* 时验证 *帖子* 是否存在。

我们称这个规则为 `exists`：

[source, js]
----
const Validator = use('Validator')
const Database = use('Database')

const existsFn = async (data, field, message, args, get) => {
  const value = get(data, field)
  if (!value) {
    /**
     * 如果未定义值，则跳过验证，必要规则
     * 应该处理好它
    */
    return
  }

  const [table, column] = args
  const row = await Database.table(table).where(column, value).first()

  if (!row) {
    throw message
  }
}

Validator.extend('exists', existsFn)
----

我们可以这样使用我们的新 `exists` 规则：

[source, js]
----
get rules () {
  return {
    post_id: 'exists:posts,id'
  }
}
----

NOTE: 由于扩展 `验证器` 的代码仅需执行一次，因此你可以使用 link:service-providers[服务提供者] 或 link:ignitor[启动装置的钩子] 来执行。请阅读 link:extending-adonisjs[核心扩展] 了解更多信息。
